Ecom_Book/Areas/Admin/Controllers/CategoryController.cs
using Ecom_Book.DataAccess.Repository.IRepository;
using Ecom_Book.Models;
using Ecom_Book.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecom_Book.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public CategoryController (IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Category category = new Category();
            if (id == null)
                return View(category);
            category = _UnitOfWork.Category.Get(id.GetValueOrDefault());
            if (category == null)
                return NotFound();
            return View(category);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category category)
        {
            if (category == null)
                return NotFound();
            if (!ModelState.IsValid)
                return View(category);
            if (category.ID == 0)
                _UnitOfWork.Category.Add(category);
            else
                _UnitOfWork.Category.Update(category);
            _UnitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
     

        #region APIs
        [HttpGet]
         
        
        public IActionResult GetAll()
        {
            var CategoryList = _UnitOfWork.Category.GetAll();
            return Json(new { data = CategoryList });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var categoryindb = _UnitOfWork.Category.Get(id);
            if (categoryindb == null)
            {
                return Json(new { success = false, messege = "error accured while deleting data" });
            }
            else
            { 
            _UnitOfWork.Category.Remove(categoryindb);
            _UnitOfWork.Save();
            return Json(new { success = true, messege = "data Deleted successfully" });
            }
        }
        #endregion
    }
}

Ecom_Book/Areas/Admin/Controllers/CompanyController.cs
using Ecom_Book.DataAccess.Repository.IRepository;
using Ecom_Book.Models;
using Ecom_Book.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecom_Book.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]

    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Company company = new Company();
            if (id == null)
                return View(company);
            company = _UnitOfWork.Company.Get(id.GetValueOrDefault());
            if (company == null)
                return NotFound();
            return View(company);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company)
        {
            if (company == null)
                return NotFound();
            if (!ModelState.IsValid)
                return View(company);
            if (company.ID == 0)
                _UnitOfWork.Company.Add(company);
            else
                _UnitOfWork.Company.Update(company);
            _UnitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }


        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _UnitOfWork.Company.GetAll() });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var companyFromDb = _UnitOfWork.Company.Get(id);
            if (companyFromDb == null)
                return Json(new { success = false, messege = "something went wrong" });
            _UnitOfWork.Company.Remove(companyFromDb);
            _UnitOfWork.Save();
            return Json(new { success = true, messege = "deleted successfully" });
        }
        #endregion
    }
}

Ecom_Book/Areas/Admin/Controllers/ProductController.cs
using Ecom_Book.DataAccess.Repository;
using Ecom_Book.DataAccess.Repository.IRepository;
using Ecom_Book.Models;
using Ecom_Book.Models.ViewModels;
using Ecom_Book.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Ecom_Book.Areas.Admin.Controllers
{  //3
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class ProductController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _UnitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                product = new Product(),
                CategoryList = _UnitOfWork.Category.GetAll().Select(cl => new SelectListItem()
                {
                    Text = cl.Name,
                    Value = cl.ID.ToString()
                }),
                CoverTypeList = _UnitOfWork.CoverType.GetAll().Select(ct=>new SelectListItem()
                {
                    Text=ct.Name,
                    Value=ct.ID.ToString()
                }),
            };
            if (id == null)
                return View(productVM);
            productVM.product = _UnitOfWork.Product.Get(id.GetValueOrDefault());
            return View(productVM);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var Uploads = Path.Combine(webRootPath, @"Images\Products");
                    if (productVM.product.ID != 0)
                    {
                        var imageExist = _UnitOfWork.Product.Get(productVM.product.ID).ImageUrl;
                        productVM.product.ImageUrl = imageExist;
                    }
                    if (productVM.product.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, productVM.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(Uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    productVM.product.ImageUrl = @"\Images\Products\" + fileName + extension;
                }
                else
                {
                    if (productVM.product.ID != 0)
                    {
                        var imageExist = _UnitOfWork.Product.Get(productVM.product.ID).ImageUrl;
                        productVM.product.ImageUrl = imageExist;
                    }
                }
                if (productVM.product.ID == 0)
                    _UnitOfWork.Product.Add(productVM.product);
                else
                    _UnitOfWork.Product.Update(productVM.product);
                _UnitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                productVM = new ProductVM()
                //product = new Product()
                {
                    product = new Product(),
                    CategoryList = _UnitOfWork.Category.GetAll().Select(cl => new SelectListItem()
                    {
                        Text = cl.Name,
                        Value = cl.ID.ToString()
                    }),
                    CoverTypeList = _UnitOfWork.CoverType.GetAll().Select(ct => new SelectListItem()
                    {
                        Text = ct.Name,
                        Value = ct.ID.ToString()
                    }),
                };
                if (productVM.product.ID != 0)
                {
                    productVM.product = _UnitOfWork.Product.Get(productVM.product.ID);
                }
                return View(productVM);
            }
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var ProductList = _UnitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
            return Json(new { data = ProductList });
        }
        
        

        

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var productindb = _UnitOfWork.Product.Get(id);
            //image delete from folder
            if (productindb.ImageUrl != "")
            {
                var imageExist = _UnitOfWork.Product.Get(productindb.ID).ImageUrl;
                productindb.ImageUrl = imageExist;
            }
            if (productindb.ImageUrl != null)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var imagePath = Path.Combine(webRootPath, productindb.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }
            //image delete from folder end

            if (productindb == null)
                return Json(new { success =false, messege = "something went wrong while deleting" });
            else
                _UnitOfWork.Product.Remove(productindb);
            _UnitOfWork.Save();
            return Json(new { success = true,messege="Data deleted successfully" }) ;
        }

        #endregion
    }
}

Ecom_Book/Areas/Admin/Controllers/UserController.cs
using Ecom_Book.DataAccess.Data;
using Ecom_Book.Models;
using Ecom_Book.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecom_Book.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]

    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserController(ApplicationDbContext context)
        {
            _context= context;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _context.ApplicationUsers.Include(c => c.Company).ToList();//aspnetUsers
            var roles = _context.Roles.ToList();    //aspnetRoles
            var userRoles = _context.UserRoles.ToList();    //aspnetUserRoles
            foreach(var user in userList)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(r => r.Id == roleId).Name;
                if(user.Company==null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }
            }
            if(!User.IsInRole(SD.Role_Admin))
            {
                var adminUser = userList.FirstOrDefault(u => u.Role == SD.Role_Admin);
                userList.Remove(adminUser);
            }
            return Json(new { data = userList });
        }
        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {
            bool isLocked = false;
            var userinDb = _context.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (userinDb == null)
                return Json(new { success = false, messege = "something went wrong while lock and unlock" });
            if(userinDb!=null && userinDb.LockoutEnd>DateTime.Now)
            {
                userinDb.LockoutEnd = DateTime.Now; ;
                isLocked = true;
            }
            else
            {
                userinDb.LockoutEnd = DateTime.Now.AddYears(100);
                isLocked = false;
            }
            _context.SaveChanges();
            return Json(new { success = true, messege = isLocked == true ? "user locked successfully" : "user unlocked successfully" });
        }
        #endregion

    }
}

Ecom_Book/Views/Shared/_CreateAndBackToList.cshtml
<div class=" row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">
            CREATE
        </button>
    </div>
    <div class=" col">
        <a asp-action="Index" class=" btn btn-success form-control">
            BACK TO LIST
        </a>
    </div>
</div>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Ecom_Book/Views/Shared/_EditAndBackTOListButton.cshtml
<div class=" row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">
            UPDATE
        </button>
    </div>
    <div class=" col">
        <a asp-action="Index" class=" btn btn-success form-control">
            BACK TO LIST
        </a>
    </div>
</div>

Ecom_Book/Views/Shared/_Layout.cshtml
@using Ecom_Book.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecom_Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <link rel="stylesheet" href="~/css/3rd party css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/3rd party css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/3rd party css/sweetalert.min.css" />
    <link rel="stylesheet" href="~/css/3rd party css/toastr.min.css" />



    @*Third Party CSS*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />



</head>
<body class="bg-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Shopping App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i>&nbsp; Home
                            </a>
                        </li>


                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    ContentManager
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>

                                </div>
                            </li>

                        }

                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Company / Users
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </div>
                            </li>
                        }
                        @if (httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_session) != null && httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_session) != 0)
                        {
                            var count = httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_session);
                            <li>
                                <a class="nav-link text-white" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="fas fa-user-shield"></i>
                            Privacy</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Ecom_Book - <a asp-area="" asp-controller="Home" asp-action="Privacy">Book Shopping Web Application</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>




    @*Third Party JS*@
    <script src="~/js/3rd party js/jquery.dataTables.min.js"></script>
    <script src="~/js/3rd party js/sweetalert.min.js"></script>
    <script src="~/js/3rd party js/toastr.min.js"></script>
    <script src="~/js/3rd party js/jquery-ui.min.js"></script>
    <script src="~/js/3rd party js/e19c476714.js"></script>





    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>